version: "3.8"

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      # Timezone
      - GENERIC_TIMEZONE=Asia/Ho_Chi_Minh
      - TZ=Asia/Ho_Chi_Minh

      # Cấu hình cơ bản

      # Tài khoản đăng nhập (đổi theo ý bạn)
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123

      # Dữ liệu lưu trữ
      - DB_TYPE=sqlite
      - DB_SQLITE_DATABASE=/home/node/.n8n/database.sqlite

      # Tắt telemetry
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_VERSION_NOTIFICATIONS_ENABLED=false
      - N8N_SECURE_COOKIE=false

      - N8N_HOST=app1.oop.vn
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://app1.oop.vn:5678/
      - N8N_SECURE_COOKIE=false        # vẫn cần vì dùng http      

    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
    driver: local